// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.1

// Built By: go install

package enums

import (
	"errors"
	"fmt"
)

const (
	// WsMessageTypeEcho is a WsMessageType of type echo.
	WsMessageTypeEcho WsMessageType = "echo"
	// WsMessageTypeJoinRoom is a WsMessageType of type join_room.
	WsMessageTypeJoinRoom WsMessageType = "join_room"
	// WsMessageTypeRoomUserList is a WsMessageType of type room_user_list.
	WsMessageTypeRoomUserList WsMessageType = "room_user_list"
	// WsMessageTypeSignal is a WsMessageType of type signal.
	WsMessageTypeSignal WsMessageType = "signal"
	// WsMessageTypeReturningSignal is a WsMessageType of type returning_signal.
	WsMessageTypeReturningSignal WsMessageType = "returning_signal"
)

var ErrInvalidWsMessageType = errors.New("not a valid WsMessageType")

// String implements the Stringer interface.
func (x WsMessageType) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x WsMessageType) IsValid() bool {
	_, err := ParseWsMessageType(string(x))
	return err == nil
}

var _WsMessageTypeValue = map[string]WsMessageType{
	"echo":             WsMessageTypeEcho,
	"join_room":        WsMessageTypeJoinRoom,
	"room_user_list":   WsMessageTypeRoomUserList,
	"signal":           WsMessageTypeSignal,
	"returning_signal": WsMessageTypeReturningSignal,
}

// ParseWsMessageType attempts to convert a string to a WsMessageType.
func ParseWsMessageType(name string) (WsMessageType, error) {
	if x, ok := _WsMessageTypeValue[name]; ok {
		return x, nil
	}
	return WsMessageType(""), fmt.Errorf("%s is %w", name, ErrInvalidWsMessageType)
}
